# Generated by Django 5.2.7 on 2026-02-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Products', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='shg_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.shg_group_registration'),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customerform'),
        ),
        migrations.AddField(
            model_name='products',
            name='shg_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.shg_group_registration'),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
