# Generated by Django 5.2.7 on 2026-02-04 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shg_Group_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shg', models.CharField(max_length=50)),
                ('date_of_formation', models.DateField()),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=15)),
                ('taluka', models.CharField(max_length=15)),
                ('district', models.CharField(choices=[('North Goa', 'North Goa'), ('South Goa', 'South Goa')], default='North Goa', max_length=20)),
                ('type_of_shg', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Mixed', 'Mixed')], default='Women', max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('shg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time_of_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('shipped_order', models.BooleanField(default=False)),
                ('delivered_order', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customerform')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer_orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('shg_groups_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.shg_group_registration')),
            ],
        ),
    ]
